### ISSUE TITLE
Mario stuck :(

### ISSUE THREAD

**Issue by vincegre** [witnessmenow/LED-Matrix-Display-Examples#4]
Hi

Thanks for sharing your sample code to use with LED Matrix display. I loaded with success the Banana code and I got the banana playing on display ! I tried also the Mario but It just displays a fixed mario screen ! Isn't is supposed to be animated like the banana ?
![IMG_20200331_122005](https://user-images.githubusercontent.com/3164888/78016416-1200b880-734b-11ea-90be-27ecee935cdd.jpg)

Thanks and stay safe ;)

Vincèn

**Comment by witnessmenow** [comment]
Hello!

Mario is just a static image so he will not move

Brian

**Comment by vincegre** [comment]
> Hello! Mario is just a static image so he will not move Brian

Ah oki sorry for confusion ;) thanks still for the share of these sketches :)

Vincèn
